# GoReleaser configuration for TinyBrain
# See https://goreleaser.com for documentation

version: 2

before:
  hooks:
    # Run tests before building
    - go test -v ./cmd/server

builds:
  - id: server
    main: ./cmd/server
    binary: server
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    # Ignore invalid combinations
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.BuildTime={{.Date}}
      - -X main.GoVersion={{.Env.GOVERSION}}

archives:
  - id: tinybrain
    format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE
      - config.example.json

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^ci:'
  groups:
    - title: Features
      regexp: '^feat:'
      order: 0
    - title: Bug Fixes
      regexp: '^fix:'
      order: 1
    - title: Others
      order: 999

release:
  github:
    owner: rainmana
    name: tinybrain
  name_template: "{{.ProjectName}} {{.Version}}"
  header: |
    ## TinyBrain {{ .Tag }} Release
    
    Security-focused LLM memory storage with intelligence gathering capabilities.
    
    ### Installation
    
    **Using go install:**
    ```bash
    go install github.com/rainmana/tinybrain/cmd/server@{{ .Tag }}
    ```
    
    **Download pre-built binary:**
    Download the appropriate binary for your platform below.
    
  footer: |
    ### Platform Notes
    
    - **macOS (Apple Silicon)**: Download the `Darwin_arm64` version
    - **macOS (Intel)**: Download the `Darwin_x86_64` version
    - **Linux**: Download the `Linux_x86_64` or `Linux_arm64` version
    - **Windows**: Download the `Windows_x86_64.zip` version
    
    ### Quick Start
    
    After downloading and extracting:
    ```bash
    # Make executable (Linux/macOS)
    chmod +x server
    
    # Run the server
    ./server serve
    
    # Or with custom port
    ./server serve --http=127.0.0.1:9000
    ```
    
    For full documentation, visit the [README](https://github.com/rainmana/tinybrain).
